% End-to-end NEVIS workflow demo: build dataset -> inversion -> forward model.
%
% See inversion/INVERSION.md for the inversion contract, and
% data/DATA_PIPELINES.md for the dataset builders.

addpath('data/pipelines');
addpath('inversion');
addpath('src');

%% 1. Build the dataset
% Use the canonical default bbox for this regression test. This keeps the
% grid compatible with the legacy inversion source state and 0365.mat
% initial hydrology file.
output_dir = './data/datasets/nevis_2022_140km_rebuilt';
bbox_km = [];
report = build_nevis_dataset(output_dir, [], bbox_km);

%% 2. Inversion
% Recovers the basal sliding parameter C_hat from observed velocity.
% Outputs land under <cfg.dataset.root>/inversions/<cfg.name>/.
%
% Loads the template config and re-points it at the dataset built above.
% The derived config is saved as a .mat next to the dataset so the run is
% reproducible. For this default-bbox regression, keep the legacy source
% state and initial hydrology so the new config-driven interface is tested
% against nevis_inv_C_legacy.m with the same inversion inputs.
clear cfg
run('./cases/nevis_inversion.m');
[~, dataset_name] = fileparts(output_dir);
cfg.dataset.name = dataset_name;
cfg.dataset.root = output_dir;
cfg.name = sprintf('%s_%s_legacy_initial_hydrology', cfg.name, dataset_name);
cfg.output.inversion_file = fullfile('inversions', cfg.name, 'C_inversion_results.mat');
cfg.output.initial_hydrology_file = fullfile('inversions', cfg.name, 'velocity_inverted.mat');
cfg.output.intermediate_prefix = fullfile('inversions', cfg.name, 'C_inversion_outer');
cfg.output.intermediate_hydrology_file = fullfile('inversions', cfg.name, 'velocity_inverted_outer.mat');
cfg.source.casename = 'n2d_region_ice_inversion_ns3';
cfg.source.state_file = './data/redundant/n2d_region_ice_inversion_ns3/n2d_region_ice_inversion_ns3.mat';
cfg.initial_hydrology.mode = 'file';
cfg.initial_hydrology.file = './data/redundant/n2d_region_ice_inversion_ns3/0365.mat';
cfg.initial_hydrology.variable = 'vv';
inv_config = fullfile(output_dir, 'nevis_inversion.mat');
save(inv_config, 'cfg');
[inv, vv_hydro, summary] = nevis_run_inversion(inv_config);

%% 3. Forward regional model
% Bind the forward run to the same rebuilt dataset and inversion products
% generated above. The forward case must not use the generic nevis_regional
% config, because that config points at data/datasets/nevis_2022_140km.
prepare_rebuilt_forward_dataset(output_dir);
[tt, vv, info, state] = n2d_regional_template('nevis_regional_rebuilt_legacy_forward');


function prepare_rebuilt_forward_dataset(output_dir)
reference_dir = './data/datasets/nevis_2022_140km';

copy_dataset_file(reference_dir, output_dir, 'nevis_170207a.mat');
copy_dataset_file(reference_dir, output_dir, ...
    fullfile('mechanistic_drainage_catalogue_2022-main', 'catalogues', ...
    'environs_lakes_2022B_250505_archive.mat'));
write_rebuilt_manifest(output_dir);
end


function copy_dataset_file(reference_dir, output_dir, relpath)
src = fullfile(reference_dir, relpath);
dst = fullfile(output_dir, relpath);
if exist(src, 'file') ~= 2
    error('test:MissingReferenceData', ...
        'Reference dataset file required for forward setup is missing: %s', src);
end
dst_dir = fileparts(dst);
if exist(dst_dir, 'dir') ~= 7
    mkdir(dst_dir);
end
if exist(dst, 'file') ~= 2
    copyfile(src, dst);
end
end


function write_rebuilt_manifest(output_dir)
manifest_file = fullfile(output_dir, 'dataset_manifest.m');
fid = fopen(manifest_file, 'w');
if fid == -1
    error('test:ManifestWrite', 'Could not write manifest: %s', manifest_file);
end
cleaner = onCleanup(@() fclose(fid));

lines = {
    '% Auto-generated by test.m for the rebuilt default-bbox regression dataset.'
    ''
    'dataset = struct;'
    'dataset.name = ''nevis_2022_140km_rebuilt'';'
    'dataset.version = ''2026-06-02'';'
    'dataset.description = ''Rebuilt NEVIS 2022 140 km dataset with forward-model auxiliary inputs.'';'
    ''
    'dataset.geometry.file = ''geometry.mat'';'
    'dataset.geometry.variable = ''geometry'';'
    'dataset.geometry.fields = {''X_m'', ''Y_m'', ''B_m'', ''S_m''};'
    ''
    'dataset.velocity.file = ''velocity.mat'';'
    'dataset.velocity.variable = ''velocity'';'
    'dataset.velocity.fields = {''u_obs_dim'', ''v_obs_dim''};'
    'dataset.velocity.units = ''m_per_year'';'
    ''
    'dataset.inversion.file = ''C_inversion_results.mat'';'
    'dataset.inversion.files = {''C_inversion_results.mat''};'
    'dataset.inversion.directory = ''inversions'';'
    'dataset.inversion.required_variables = {''C_hat'', ''u_obs_noisy'', ...'
    '    ''v_obs_noisy'', ''N_current'', ''aa'', ''pp'', ''gg'', ''oo'', ''ps''};'
    ''
    'dataset.initial_hydrology.file = ''velocity_inverted.mat'';'
    'dataset.initial_hydrology.files = {''velocity_inverted.mat''};'
    'dataset.initial_hydrology.directory = ''inversions'';'
    'dataset.initial_hydrology.variable = ''vv_hydro'';'
    'dataset.initial_hydrology.required_fields = {''N''};'
    'dataset.initial_hydrology.optional_fields = {''u'', ''v''};'
    ''
    'dataset.moulins.file = ''nevis_170207a.mat'';'
    'dataset.moulins.variable = ''pp'';'
    'dataset.moulins.fields = {''ni_m'', ''sum_m''};'
    ''
    'dataset.lakes.file = ''mechanistic_drainage_catalogue_2022-main/catalogues/environs_lakes_2022B_250505_archive.mat'';'
    'dataset.lakes.variable = ''environs_lakes'';'
    ''
    'dataset.runoff.file = ''racmo_runoff_2022.mat'';'
    'dataset.runoff.variable = ''racmo_runoff_2022'';'
    'dataset.runoff.units = ''mm_we_per_day'';'
    ''
    'dataset.stations.file = ''station_timeseries_2022.mat'';'
    'dataset.stations.variable = ''station_data'';'
    'dataset.stations.fields = {''x_m'', ''y_m''};'
    };

for i = 1:numel(lines)
    fprintf(fid, '%s\n', lines{i});
end
end
