#!/usr/bin/env python3
"""Generate idealized convergence-test NEVIS case configs.

This replaces the old MATLAB script generator. It writes configs into ./cases;
run them with n2d_idealized_template(casename), or with nevis_run.sh using the
default idealized workflow.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path


CASE_LABEL = "test"

CONVERGENCE_COMBINATIONS = [
    # moulin_input, Dx, kappa, mu, V, theta
    (0, 1000, 1e-99, 1e-3, 1e6, 0.0),
    (0, 500, 1e-99, 1e-3, 1e6, 0.0),
    (0, 250, 1e-99, 1e-3, 1e6, 0.0),
    (0, 125, 1e-99, 1e-3, 1e6, 0.0),
    (0, 62.5, 1e-99, 1e-3, 1e6, 0.0),
    (0, 31.25, 1e-99, 1e-3, 1e6, 0.0),
    (0, 15.625, 1e-99, 1e-3, 1e6, 0.0),
    (0, 7.8125, 1e-99, 1e-3, 1e6, 0.0),
]


def matlab_number(value: float | int) -> str:
    return f"{value:.12g}"


def sci_name(value: float | int) -> str:
    text = f"{float(value):.0e}"
    mantissa, exponent = text.split("e")
    exponent = exponent.replace("+", "").replace("-", "_")
    return f"{mantissa}e{exponent}"


def case_name(moulin_input: float, dx: float, kappa: float, mu: float, volume: float, theta: float) -> str:
    label = f"{CASE_LABEL}_" if CASE_LABEL else ""
    volume_log10 = int(round(math.log10(volume)))
    return (
        f"n1d_{label}E{matlab_number(moulin_input).replace('.', '_')}"
        f"_mu{sci_name(mu)}_kappa{sci_name(kappa)}_V1e{volume_log10}"
        f"_theta{sci_name(theta)}_DX{sci_name(dx)}_convergence"
    )


def config_text(casename: str, moulin_input: float, dx: float, kappa: float, mu: float, volume: float, theta: float) -> str:
    length_m = 5e4
    nx_expr = int(round(length_m / dx)) + 1
    return f"""% Auto-generated idealized NEVIS convergence case config.
% Generated by ./srcgen/convergence_test_scripts.py.
% Run with: n2d_idealized_template('{casename}')

run(fullfile(fileparts(mfilename('fullpath')), 'nevis_idealized.m'));

cfg.casename = '{casename}';
cfg.case_root = './cases';

cfg.pd.kappa_b = {matlab_number(kappa)};
cfg.pd.mu = {matlab_number(mu)};
cfg.pd.N_reg1 = 1e3;
cfg.pd.N_reg2 = 1e4;
cfg.pd.sigma = 0e-3;
cfg.pd.k_s = 1e-3;
cfg.pd.tau_b = 60e3;
cfg.pd.melt = @(pd) 0*(pd.G+(pd.u_b*pd.tau_b))/pd.rho_w/pd.L;
cfg.pd.meltinterior = @(pd) ((pd.G+((100/pd.ty)*pd.tau_b))/pd.rho_w/pd.L)*1e3;
cfg.pd.E_lapse = @(pd) 40/1000/pd.td/10^3;
cfg.pd.hb_reg1 = 1e-3;
cfg.pd.hb_reg2 = 1e-3;
cfg.pd.B_reg = 0;

cfg.geometry.mode = 'function';
cfg.geometry.length_m = {matlab_number(length_m)};
cfg.geometry.width_ratio = 1.0;
cfg.geometry.nx = {nx_expr};
cfg.geometry.ny = 1;
cfg.geometry.min_thickness_m = 0;
cfg.geometry.bed_function = @(X,Y,L,W,pd,ps,pp,gg,oo,cfg) ...
    5e4 - {matlab_number(theta)}.*X;
cfg.geometry.surface_function = @(X,Y,L,W,pd,ps,pp,gg,oo,cfg) ...
    1000 + 5e4 - {matlab_number(theta)}.*X;

cfg.initial_hydrology.mode = 'k_factor_cavity_equilibrium';
cfg.initial_hydrology.k_factor = 0.9;

cfg.moulins.mode = 'coordinates_fractional';
cfg.moulins.x_fraction = [0.25];
cfg.moulins.y_fraction = [0.0];
cfg.moulins.input_m3_per_s = {matlab_number(moulin_input)};
cfg.moulins.input_ramp_days = 30;

cfg.lakes.mode = 'coordinates_fractional';
cfg.lakes.x_fraction = 0.25;
cfg.lakes.y_fraction = 0.0;
cfg.lakes.volume_m3 = {matlab_number(volume)};
cfg.lakes.drainage_day = 10;
cfg.lakes.duration_days = 0.025;

cfg.input.runoff_max_mm_per_day = 0;
cfg.input.moulin_input_m3_per_s = {matlab_number(moulin_input)};
cfg.input.ramp_days = 30;

cfg.run.dt_days = 1/24;
cfg.run.t_span_days = 0:0.005:50;
cfg.run.save_timesteps = true;
cfg.run.save_pts_all = true;
"""


def write_file(path: Path, text: str, overwrite: bool) -> bool:
    if path.exists() and not overwrite:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", default="./cases", help="Directory for generated case configs.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing configs.")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    written = []
    skipped = []
    for moulin_input, dx, kappa, mu, volume, theta in CONVERGENCE_COMBINATIONS:
        name = case_name(moulin_input, dx, kappa, mu, volume, theta)
        path = out_dir / f"{name}.m"
        if write_file(path, config_text(name, moulin_input, dx, kappa, mu, volume, theta), args.overwrite):
            written.append(path.name)
        else:
            skipped.append(path.name)

    print(f"Generated {len(written)} convergence configs in {out_dir}.")
    if skipped:
        print(f"Skipped {len(skipped)} existing configs; use --overwrite to replace them.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
