#!/usr/bin/env python3
"""Generate reference idealized NEVIS case configs.

This replaces the old notebook/script generator. It writes lightweight config
files into ./cases; the configs are run with n2d_idealized_template(casename).
"""

from __future__ import annotations

import argparse
from pathlib import Path


PARAM_COMBOS = [
    (0, 1e3, 1e-10, 7),
    (1, 1e3, 1e-10, 7),
    (10, 1e3, 1e-10, 7),
    (100, 1e3, 1e-10, 7),
    (0, 1e3, 1e-10, 8),
    (1, 1e3, 1e-10, 8),
    (10, 1e3, 1e-10, 8),
    (100, 1e3, 1e-10, 8),
]

CASE_LABEL = "test"


def matlab_number(value: float | int) -> str:
    if isinstance(value, int):
        return str(value)
    return f"{value:.12g}"


def sci_name(value: float) -> tuple[str, str]:
    mantissa, exponent = f"{value:.0e}".split("e")
    mantissa = mantissa.replace(".", "")
    exponent = exponent.replace("-", "_").replace("+", "")
    return mantissa, exponent


def spinup_case_name(moulin_input: int, mu: float, kappa: float) -> str:
    mu_m, mu_e = sci_name(mu)
    k_m, k_e = sci_name(kappa)
    label = f"{CASE_LABEL}_" if CASE_LABEL else ""
    return f"n2d_{label}{moulin_input}m3s_kappa{k_m}e{k_e}_mu{mu_m}e{mu_e}_hbreg5e_3_spinup"


def drainage_case_name(spinup_case: str, volume_log10: int) -> str:
    return spinup_case.replace("_spinup", f"_V1e{volume_log10}_drainage")


def config_header(casename: str) -> str:
    return f"""% Auto-generated idealized NEVIS case config.
% Generated by ./reference_scripts.py.
% Run with: n2d_idealized_template('{casename}')

cfg = struct;
cfg.casename = '{casename}';
cfg.case_root = './cases';

"""


def common_config(mu: float, kappa: float, moulin_input: int) -> str:
    return f"""%% Model and solver options
cfg.oo.evaluate_variables = 1;
cfg.oo.input_gaussian = 1;
cfg.oo.relaxation_term = 1;
cfg.oo.initial_condition = 1;
cfg.oo.mean_perms = 1;
cfg.oo.include_blister = 1;
cfg.oo.include_ice = 0;
cfg.oo.display_residual = 0;
cfg.oo.adjust_boundaries = 1;
cfg.oo.yperiodic = 1;
cfg.oo.xperiodic = 0;
cfg.oo.keep_all_moulins = 0;
cfg.oo.random_moulins = 0;
cfg.oo.random_lakes = 0;
cfg.oo.surface_runoff = 0;
cfg.oo.RACMO_runoff = 0;
cfg.oo.distributed_input = 0;
cfg.oo.save_timesteps = 1;
cfg.oo.save_pts_all = 1;

%% Dimensional physical parameters
cfg.pd.alpha_b = 0;
cfg.pd.kappa_b = {matlab_number(kappa)};
cfg.pd.c0 = 1;
cfg.pd.mu = {matlab_number(mu)};
cfg.pd.Ye = 8.8e9;
cfg.pd.B = @(pd) pd.Ye*(1e3)^3/(12*(1-0.33^2));
cfg.pd.E_lapse = @(pd) 30/1000/pd.td/10^3;
cfg.pd.hb_reg1 = 5e-3;
cfg.pd.hb_reg2 = 1e-3;
cfg.pd.N_reg1 = 1e4;
cfg.pd.deltap_reg = 1e4;
cfg.pd.B_reg = 0;
cfg.pd.G = 0.01;
cfg.pd.melt = @(pd) pd.G/pd.rho_w/pd.L;

cfg.pp = struct;

%% Analytical geometry
cfg.geometry.mode = 'hewitt_2013_sqrt';
cfg.geometry.length_m = 5e4;
cfg.geometry.width_ratio = 0.4;
cfg.geometry.nx = 201;
cfg.geometry.ny = 80;
cfg.geometry.bed_elevation_m = 0;
cfg.geometry.surface_head_m = 1060;
cfg.geometry.surface_exponent = 0.5;
cfg.geometry.min_thickness_m = 0;

%% Moulins
cfg.moulins.mode = 'coordinates_fractional';
cfg.moulins.x_fraction = [0.25];
cfg.moulins.y_fraction = [0.50];
cfg.moulins.input_m3_per_s = {matlab_number(moulin_input)};
cfg.moulins.input_ramp_days = 30;

%% Analytical input forcing
cfg.input.runoff_max_mm_per_day = 30;
cfg.input.moulin_input_m3_per_s = {matlab_number(moulin_input)};
cfg.input.ramp_days = 30;

"""


def lake_config(volume_log10: int | None) -> str:
    volume = "0" if volume_log10 is None else f"1e{volume_log10}"
    extra = ""
    if volume_log10 is None:
        drainage_day = "0.5*365"
    else:
        drainage_day = "0"
        extra = "cfg.lakes.drainage_after_start_days = 20;\n"
    return f"""%% Supraglacial lakes
cfg.lakes.mode = 'coordinates_fractional';
cfg.lakes.x_fraction = 0.50;
cfg.lakes.y_fraction = 0.50;
cfg.lakes.volume_m3 = {volume};
cfg.lakes.drainage_day = {drainage_day};
{extra}cfg.lakes.duration_days = 0.025;

"""


def spinup_config(casename: str, moulin_input: int, mu: float, kappa: float) -> str:
    return (
        config_header(casename)
        + common_config(mu, kappa, moulin_input)
        + """%% Initial hydrology state
cfg.initial_hydrology.mode = 'k_factor_cavity_equilibrium';
cfg.initial_hydrology.k_factor = 1.00;

"""
        + lake_config(None)
        + """%% Run control
cfg.run.dt_days = 1/24;
cfg.run.t_span_days = 1:1:2*365;
"""
    )


def drainage_config(
    casename: str,
    spinup_case: str,
    moulin_input: int,
    mu: float,
    kappa: float,
    volume_log10: int,
) -> str:
    return (
        config_header(casename)
        + common_config(mu, kappa, moulin_input)
        + f"""%% Initial hydrology state
cfg.initial_hydrology.mode = 'result_timestep';
cfg.initial_hydrology.result_case = '{spinup_case}';
cfg.initial_hydrology.timestep_file = '0730.mat';

"""
        + lake_config(volume_log10)
        + """%% Stations
cfg.stations.mode = 'downstream_lake';
cfg.stations.spacing_m = 5e3;

%% Run control
cfg.run.dt_days = 1/24;
cfg.run.t_span_after_start_days = [(1:1:19) (19.9:0.001:20.1) (21:1:1.5*365)];
"""
    )


def write_file(path: Path, text: str, overwrite: bool) -> bool:
    if path.exists() and not overwrite:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", default="./cases", help="Directory for generated case configs.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing configs.")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    spinups: dict[str, tuple[int, float, float]] = {}
    for moulin_input, mu, kappa, _volume_log10 in PARAM_COMBOS:
        name = spinup_case_name(moulin_input, mu, kappa)
        spinups[name] = (moulin_input, mu, kappa)

    written_spinups = []
    skipped_spinups = []
    for name, (moulin_input, mu, kappa) in sorted(spinups.items()):
        path = out_dir / f"{name}.m"
        text = spinup_config(name, moulin_input, mu, kappa)
        if write_file(path, text, args.overwrite):
            written_spinups.append(path.name)
        else:
            skipped_spinups.append(path.name)

    written_drainage = []
    skipped_drainage = []
    for moulin_input, mu, kappa, volume_log10 in PARAM_COMBOS:
        spinup = spinup_case_name(moulin_input, mu, kappa)
        name = drainage_case_name(spinup, volume_log10)
        path = out_dir / f"{name}.m"
        text = drainage_config(name, spinup, moulin_input, mu, kappa, volume_log10)
        if write_file(path, text, args.overwrite):
            written_drainage.append(path.name)
        else:
            skipped_drainage.append(path.name)

    print(f"Generated {len(written_spinups)} spinup configs and {len(written_drainage)} drainage configs in {out_dir}.")
    if skipped_spinups or skipped_drainage:
        print(f"Skipped {len(skipped_spinups) + len(skipped_drainage)} existing configs; use --overwrite to replace them.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
