#!/usr/bin/env python3
"""Generate regional-study NEVIS case configs.

This replaces the old MATLAB script generator. It writes configs into ./cases;
run them with n2d_regional_template(casename), or set CASE_WORKFLOW=regional
when using nevis_run.sh.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path


CASE_LABEL = "test"

PARAM_COMBINATIONS = [
    # kappa, t_drainage_days, V_m3, mean_perms, H_reg_m, mu
    (1e-99, 30, 1.8e8, 1, 1000, 2e1),
    (1e-11, 30, 1.8e8, 1, 1000, 1e1),
    (1e-10, 30, 1.8e8, 1, 1000, 1e1),
    (5e-12, 30, 1.8e8, 1, 1000, 1e1),
    (1e-99, 30, 1.8e8, 1, 1000, 1e1),
]


def matlab_number(value: float | int) -> str:
    return f"{value:.12g}"


def sci_name(value: float | int) -> str:
    text = f"{float(value):.0e}"
    mantissa, exponent = text.split("e")
    exponent = exponent.replace("+", "").replace("-", "_")
    return f"{mantissa}e{exponent}"


def spinup_case_name(kappa: float, mean_perms: int, h_reg: float, mu: float) -> str:
    label = f"{CASE_LABEL}_" if CASE_LABEL else ""
    h_reg_text = matlab_number(h_reg).replace(".", "_")
    return (
        f"n2d_region_{label}melt_meanperms{mean_perms}_Hreg{h_reg_text}"
        f"_kappa{sci_name(kappa)}_mu{sci_name(mu)}_spinup"
    )


def drainage_case_name(spinup_case: str, t_drainage: float, volume: float) -> str:
    volume_log10 = int(round(math.log10(volume)))
    return spinup_case.replace(
        "_spinup",
        f"_td{matlab_number(t_drainage).replace('.', '_')}_V1e{volume_log10}_drainage",
    )


def common_overrides(casename: str, kappa: float, mean_perms: int, h_reg: float, mu: float) -> str:
    return f"""run(fullfile(fileparts(mfilename('fullpath')), 'nevis_regional.m'));

cfg.casename = '{casename}';
cfg.case_root = './cases';

cfg.oo.include_ice = 0;
cfg.oo.mean_perms = {int(mean_perms)};
cfg.oo.modified_mean_perms = 0;
cfg.oo.display_residual = 0;

cfg.pd.kappa_b = {matlab_number(kappa)};
cfg.pd.mu = {matlab_number(mu)};
cfg.pd.k_s = 1e-3;
cfg.pd.melt = @(pd) (pd.G+(pd.u_b*pd.tau_b))/pd.rho_w/pd.L;
cfg.pd.meltinterior = @(pd) 0*((pd.G+((100/pd.ty)*pd.tau_b))/pd.rho_w/pd.L)*1e3;
cfg.pd.B_reg = @(pd) pd.Ye*({matlab_number(h_reg)})^3/(12*(1-0.33)^2);

cfg.initial_hydrology.mode = 'k_factor';
cfg.initial_hydrology.k_factor = 0.9;

cfg.runoff.surface_runoff = false;
cfg.runoff.RACMO_runoff = true;
cfg.runoff.distributed_input = false;
cfg.runoff.meltE_mm_per_day = 0;
cfg.runoff.subtract_lake_volume = false;
"""


def spinup_config(casename: str, kappa: float, mean_perms: int, h_reg: float, mu: float) -> str:
    return f"""% Auto-generated regional NEVIS spinup case config.
% Generated by ./srcgen/regional_study_scripts.py.
% Run with: n2d_regional_template('{casename}')

{common_overrides(casename, kappa, mean_perms, h_reg, mu)}
cfg.lakes.mode = 'manual';
cfg.lakes.x_m = 40e3;
cfg.lakes.y_m = -20e3;
cfg.lakes.volume_m3 = 0;
cfg.lakes.drainage_day = 30;
cfg.lakes.duration_days = 0.025;

cfg.stations.mode = 'coordinates';
cfg.stations.x_m = [40e3, 40e3, 20e3, 0, -40e3];
cfg.stations.y_m = [-15e3, -5e3, -15e3, -25e3, -30e3];

cfg.run.t_span_days = 1:1:365*5;
cfg.run.save_timesteps = true;
cfg.run.save_pts_all = true;
"""


def drainage_config(
    casename: str,
    spinup_case: str,
    kappa: float,
    t_drainage: float,
    volume: float,
    mean_perms: int,
    h_reg: float,
    mu: float,
) -> str:
    return f"""% Auto-generated regional NEVIS drainage case config.
% Generated by ./srcgen/regional_study_scripts.py.
% Run with: n2d_regional_template('{casename}')

{common_overrides(casename, kappa, mean_perms, h_reg, mu)}
cfg.initial_hydrology.mode = 'result_timestep';
cfg.initial_hydrology.result_case = '{spinup_case}';
cfg.initial_hydrology.timestep_file = '1825.mat';

cfg.lakes.mode = 'manual';
cfg.lakes.x_m = 40e3;
cfg.lakes.y_m = -20e3;
cfg.lakes.volume_m3 = {matlab_number(volume)};
cfg.lakes.drainage_after_start_days = {matlab_number(t_drainage)};
cfg.lakes.duration_days = 0.025;

cfg.stations.mode = 'coordinates';
cfg.stations.x_m = [40e3, 40e3, 20e3, 0, -40e3];
cfg.stations.y_m = [-15e3, -5e3, -15e3, -25e3, -30e3];

cfg.run.t_span_after_start_days = [(1:1:29) (29.9:0.001:30.1) (31:1:120)];
cfg.run.save_timesteps = true;
cfg.run.save_pts_all = true;
"""


def write_file(path: Path, text: str, overwrite: bool) -> bool:
    if path.exists() and not overwrite:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", default="./cases", help="Directory for generated case configs.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing configs.")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    written_spinups = []
    written_drainage = []
    skipped = []
    unique_spinups: dict[str, tuple[float, int, float, float]] = {}
    for kappa, _t_drainage, _volume, mean_perms, h_reg, mu in PARAM_COMBINATIONS:
        name = spinup_case_name(kappa, mean_perms, h_reg, mu)
        unique_spinups[name] = (kappa, mean_perms, h_reg, mu)

    for name, (kappa, mean_perms, h_reg, mu) in sorted(unique_spinups.items()):
        path = out_dir / f"{name}.m"
        if write_file(path, spinup_config(name, kappa, mean_perms, h_reg, mu), args.overwrite):
            written_spinups.append(path.name)
        else:
            skipped.append(path.name)

    for kappa, t_drainage, volume, mean_perms, h_reg, mu in PARAM_COMBINATIONS:
        spinup = spinup_case_name(kappa, mean_perms, h_reg, mu)
        name = drainage_case_name(spinup, t_drainage, volume)
        path = out_dir / f"{name}.m"
        text = drainage_config(name, spinup, kappa, t_drainage, volume, mean_perms, h_reg, mu)
        if write_file(path, text, args.overwrite):
            written_drainage.append(path.name)
        else:
            skipped.append(path.name)

    print(f"Generated {len(written_spinups)} spinup configs and {len(written_drainage)} drainage configs in {out_dir}.")
    if skipped:
        print(f"Skipped {len(skipped)} existing configs; use --overwrite to replace them.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
