% Auto-generated idealized NEVIS convergence case config.
% Generated by ./srcgen/convergence_test_scripts.py.
% Run with: n2d_idealized_template('n1d_test_E0_mu1e_03_kappa1e_99_V1e6_theta0e00_DX5e02_convergence')

run(fullfile(fileparts(mfilename('fullpath')), 'nevis_idealized.m'));

cfg.casename = 'n1d_test_E0_mu1e_03_kappa1e_99_V1e6_theta0e00_DX5e02_convergence';
cfg.case_root = './cases';

cfg.pd.kappa_b = 1e-99;
cfg.pd.mu = 0.001;
cfg.pd.N_reg1 = 1e3;
cfg.pd.N_reg2 = 1e4;
cfg.pd.sigma = 0e-3;
cfg.pd.k_s = 1e-3;
cfg.pd.tau_b = 60e3;
cfg.pd.melt = @(pd) 0*(pd.G+(pd.u_b*pd.tau_b))/pd.rho_w/pd.L;
cfg.pd.meltinterior = @(pd) ((pd.G+((100/pd.ty)*pd.tau_b))/pd.rho_w/pd.L)*1e3;
cfg.pd.E_lapse = @(pd) 40/1000/pd.td/10^3;
cfg.pd.hb_reg1 = 1e-3;
cfg.pd.hb_reg2 = 1e-3;
cfg.pd.B_reg = 0;

cfg.geometry.mode = 'function';
cfg.geometry.length_m = 50000;
cfg.geometry.width_ratio = 1.0;
cfg.geometry.nx = 101;
cfg.geometry.ny = 1;
cfg.geometry.min_thickness_m = 0;
cfg.geometry.bed_function = @(X,Y,L,W,pd,ps,pp,gg,oo,cfg) ...
    5e4 - 0.*X;
cfg.geometry.surface_function = @(X,Y,L,W,pd,ps,pp,gg,oo,cfg) ...
    1000 + 5e4 - 0.*X;

cfg.initial_hydrology.mode = 'k_factor_cavity_equilibrium';
cfg.initial_hydrology.k_factor = 0.9;

cfg.moulins.mode = 'coordinates_fractional';
cfg.moulins.x_fraction = [0.25];
cfg.moulins.y_fraction = [0.0];
cfg.moulins.input_m3_per_s = 0;
cfg.moulins.input_ramp_days = 30;

cfg.lakes.mode = 'coordinates_fractional';
cfg.lakes.x_fraction = 0.25;
cfg.lakes.y_fraction = 0.0;
cfg.lakes.volume_m3 = 1000000;
cfg.lakes.drainage_day = 10;
cfg.lakes.duration_days = 0.025;

cfg.input.runoff_max_mm_per_day = 0;
cfg.input.moulin_input_m3_per_s = 0;
cfg.input.ramp_days = 30;

cfg.run.dt_days = 1/24;
cfg.run.t_span_days = 0:0.005:50;
cfg.run.save_timesteps = true;
cfg.run.save_pts_all = true;
