% Auto-generated regional NEVIS ice-dynamics spinup case config.
% Generated by ./srcgen/ice_dynamics_scripts.py.
% Run with: n2d_regional_template('n2d_regional_test_racmo_eps1e_02_kappa5e_11_mu5e00_partition2e_01_k01e_01_spinup')

run(fullfile(fileparts(mfilename('fullpath')), 'nevis_regional.m'));

cfg.casename = 'n2d_regional_test_racmo_eps1e_02_kappa5e_11_mu5e00_partition2e_01_k01e_01_spinup';
cfg.case_root = './cases';

cfg.inversion.mode = 'file';
cfg.inversion.file = 'C_inversion_results.mat';


cfg.oo.include_ice = 1;
cfg.oo.mean_perms = 1;
cfg.oo.modified_mean_perms = 0;
cfg.oo.display_residual = 0;
cfg.oo.visualize_vel = 0;
cfg.oo.N_coupling = 1;
cfg.oo.U_coupling = 1;
cfg.oo.boundary_method = 'stress_l_vel_tbl';
cfg.oo.mask_boundary_method = 'stress_free';
cfg.oo.plot_residual = 0;
cfg.oo.max_iter_new = 50;
cfg.oo.partition_ratio = 0.2;
cfg.oo.iterative_solver = 0;

cfg.pd.kappa_b = 5e-11;
cfg.pd.mu = 5;
cfg.pd.k_s = 0.1;
cfg.pd.melt = @(pd) (pd.G+(pd.u_b*pd.tau_b))/pd.rho_w/pd.L;
cfg.pd.meltinterior = @(pd) 0*((pd.G+((100/pd.ty)*pd.tau_b))/pd.rho_w/pd.L)*1e3;
cfg.pd.B_reg = @(pd) pd.Ye*(1000)^3/(12*(1-0.33)^2);

cfg.pp.eps_reg = 0.01;
cfg.pp.Ub_reg = 1e-16;
cfg.pp.N_slide_reg = 1e-16;
cfg.pp.taud_reg = 1e-16;
cfg.pp.C2 = 0;

cfg.runoff.surface_runoff = logical(1);
cfg.runoff.RACMO_runoff = logical(1);
cfg.runoff.distributed_input = logical(0);
cfg.runoff.meltE_mm_per_day = 0;
cfg.runoff.meltE_ramp_days = 20;
cfg.runoff.smooth_days = 1;
cfg.runoff.subtract_lake_volume = true;

cfg.initial_hydrology.mode = 'file';
cfg.initial_hydrology.file = 'velocity_inverted.mat';
cfg.initial_hydrology.variable = 'vv_hydro';


cfg.lakes.mode = 'environs_lakes_catalogue';
cfg.lakes.file = 'mechanistic_drainage_catalogue_2022-main/catalogues/environs_lakes_2022B_250505_archive.mat';
cfg.lakes.variable = 'environs_lakes';
cfg.lakes.spinup_volume_scale = 1;

cfg.stations.mode = 'file';
cfg.stations.file = 'station_timeseries_2022.mat';
cfg.stations.variable = 'station_data';
cfg.stations.x_field = 'x_m';
cfg.stations.y_field = 'y_m';

cfg.run.t_span_days = [(1:1:180) (180.1:0.1:239.9) (240:1:365)];
cfg.run.save_timesteps = true;
cfg.run.save_pts_all = true;
