% Auto-generated regional NEVIS drainage case config.
% Generated by ./srcgen/regional_study_scripts.py.
% Run with: n2d_regional_template('n2d_region_test_melt_meanperms1_Hreg1000_kappa1e_99_mu2e01_td30_V1e8_drainage')

run(fullfile(fileparts(mfilename('fullpath')), 'nevis_regional.m'));

cfg.casename = 'n2d_region_test_melt_meanperms1_Hreg1000_kappa1e_99_mu2e01_td30_V1e8_drainage';
cfg.case_root = './cases';

cfg.oo.include_ice = 0;
cfg.oo.mean_perms = 1;
cfg.oo.modified_mean_perms = 0;
cfg.oo.display_residual = 0;

cfg.pd.kappa_b = 1e-99;
cfg.pd.mu = 20;
cfg.pd.k_s = 1e-3;
cfg.pd.melt = @(pd) (pd.G+(pd.u_b*pd.tau_b))/pd.rho_w/pd.L;
cfg.pd.meltinterior = @(pd) 0*((pd.G+((100/pd.ty)*pd.tau_b))/pd.rho_w/pd.L)*1e3;
cfg.pd.B_reg = @(pd) pd.Ye*(1000)^3/(12*(1-0.33)^2);

cfg.initial_hydrology.mode = 'k_factor';
cfg.initial_hydrology.k_factor = 0.9;

cfg.runoff.surface_runoff = false;
cfg.runoff.RACMO_runoff = true;
cfg.runoff.distributed_input = false;
cfg.runoff.meltE_mm_per_day = 0;
cfg.runoff.subtract_lake_volume = false;

cfg.initial_hydrology.mode = 'result_timestep';
cfg.initial_hydrology.result_case = 'n2d_region_test_melt_meanperms1_Hreg1000_kappa1e_99_mu2e01_spinup';
cfg.initial_hydrology.timestep_file = '1825.mat';

cfg.lakes.mode = 'manual';
cfg.lakes.x_m = 40e3;
cfg.lakes.y_m = -20e3;
cfg.lakes.volume_m3 = 180000000;
cfg.lakes.drainage_after_start_days = 30;
cfg.lakes.duration_days = 0.025;

cfg.stations.mode = 'coordinates';
cfg.stations.x_m = [40e3, 40e3, 20e3, 0, -40e3];
cfg.stations.y_m = [-15e3, -5e3, -15e3, -25e3, -30e3];

cfg.run.t_span_after_start_days = [(1:1:29) (29.9:0.001:30.1) (31:1:120)];
cfg.run.save_timesteps = true;
cfg.run.save_pts_all = true;
