% Auto-generated idealized NEVIS case config.
% Generated by ./reference_scripts.py.
% Run with: n2d_idealized_template('n2d_test_100m3s_kappa1e_10_mu1e03_hbreg5e_3_V1e8_drainage')

cfg = struct;
cfg.casename = 'n2d_test_100m3s_kappa1e_10_mu1e03_hbreg5e_3_V1e8_drainage';
cfg.case_root = './cases';

%% Model and solver options
cfg.oo.evaluate_variables = 1;
cfg.oo.input_gaussian = 1;
cfg.oo.relaxation_term = 1;
cfg.oo.initial_condition = 1;
cfg.oo.mean_perms = 1;
cfg.oo.include_blister = 1;
cfg.oo.include_ice = 0;
cfg.oo.display_residual = 0;
cfg.oo.adjust_boundaries = 1;
cfg.oo.yperiodic = 1;
cfg.oo.xperiodic = 0;
cfg.oo.keep_all_moulins = 0;
cfg.oo.random_moulins = 0;
cfg.oo.random_lakes = 0;
cfg.oo.surface_runoff = 0;
cfg.oo.RACMO_runoff = 0;
cfg.oo.distributed_input = 0;
cfg.oo.save_timesteps = 1;
cfg.oo.save_pts_all = 1;

%% Dimensional physical parameters
cfg.pd.alpha_b = 0;
cfg.pd.kappa_b = 1e-10;
cfg.pd.c0 = 1;
cfg.pd.mu = 1000;
cfg.pd.Ye = 8.8e9;
cfg.pd.B = @(pd) pd.Ye*(1e3)^3/(12*(1-0.33^2));
cfg.pd.E_lapse = @(pd) 30/1000/pd.td/10^3;
cfg.pd.hb_reg1 = 5e-3;
cfg.pd.hb_reg2 = 1e-3;
cfg.pd.N_reg1 = 1e4;
cfg.pd.deltap_reg = 1e4;
cfg.pd.B_reg = 0;
cfg.pd.G = 0.01;
cfg.pd.melt = @(pd) pd.G/pd.rho_w/pd.L;

cfg.pp = struct;

%% Analytical geometry
cfg.geometry.mode = 'hewitt_2013_sqrt';
cfg.geometry.length_m = 5e4;
cfg.geometry.width_ratio = 0.4;
cfg.geometry.nx = 201;
cfg.geometry.ny = 80;
cfg.geometry.bed_elevation_m = 0;
cfg.geometry.surface_head_m = 1060;
cfg.geometry.surface_exponent = 0.5;
cfg.geometry.min_thickness_m = 0;

%% Moulins
cfg.moulins.mode = 'coordinates_fractional';
cfg.moulins.x_fraction = [0.25];
cfg.moulins.y_fraction = [0.50];
cfg.moulins.input_m3_per_s = 100;
cfg.moulins.input_ramp_days = 30;

%% Analytical input forcing
cfg.input.runoff_max_mm_per_day = 30;
cfg.input.moulin_input_m3_per_s = 100;
cfg.input.ramp_days = 30;

%% Initial hydrology state
cfg.initial_hydrology.mode = 'result_timestep';
cfg.initial_hydrology.result_case = 'n2d_test_100m3s_kappa1e_10_mu1e03_hbreg5e_3_spinup';
cfg.initial_hydrology.timestep_file = '0730.mat';

%% Supraglacial lakes
cfg.lakes.mode = 'coordinates_fractional';
cfg.lakes.x_fraction = 0.50;
cfg.lakes.y_fraction = 0.50;
cfg.lakes.volume_m3 = 1e8;
cfg.lakes.drainage_day = 0;
cfg.lakes.drainage_after_start_days = 20;
cfg.lakes.duration_days = 0.025;

%% Stations
cfg.stations.mode = 'downstream_lake';
cfg.stations.spacing_m = 5e3;

%% Run control
cfg.run.dt_days = 1/24;
cfg.run.t_span_after_start_days = [(1:1:19) (19.9:0.001:20.1) (21:1:1.5*365)];
