% Forward regional case paired with test.m's rebuilt default-bbox inversion.
%
% This config inherits the regional template parameters, then rebinds the
% dataset and initialization files to the inversion products generated by
% test.m. It is intentionally separate from nevis_regional so the forward
% run cannot accidentally read the reference dataset package.

case_dir = fileparts(mfilename('fullpath'));
run(fullfile(case_dir, 'nevis_regional.m'));

cfg.casename = 'nevis_regional_rebuilt_legacy_forward';
cfg.dataset.name = 'nevis_2022_140km_rebuilt';
cfg.dataset.root = './data/datasets/nevis_2022_140km_rebuilt';
cfg.dataset.manifest = 'dataset_manifest.m';

inversion_name = 'weertman_ns3_default_nevis_2022_140km_rebuilt_legacy_initial_hydrology';

cfg.inversion.mode = 'file';
cfg.inversion.file = fullfile('inversions', inversion_name, ...
    'C_inversion_results.mat');

cfg.initial_hydrology.mode = 'file';
cfg.initial_hydrology.file = fullfile('inversions', inversion_name, ...
    'velocity_inverted.mat');
cfg.initial_hydrology.variable = 'vv_hydro';
